### ISSUE TITLE
Linux dependency on Win32::Registry

### ISSUE THREAD

**Issue by hankache** [azawawi/perl6-file-which#21]
On Linux still depends on Win32::Registry to install.

**Comment by paralogismos** [comment]
I ran across this issue today. I suspect that [this commit](https://github.com/azawawi/perl6-file-which/commit/7678660b518f5a0598f8bd83c0d0f1f3d6fb6ae7) may be the culprit.

I had a discussion about the issue with ugexe on #raku; they suggested that dependencies should probably be modified to something like this:

`"depends" : [ {"name" : { "by-distro.name" : { "win32" : "Win32::Registry", "" : "" } } } ]`

**Comment by ugexe** [comment]
Additional to the comment before mentioning updating META6.json, the code itself will need to be updated to conditionally load either File::Which::WIn32 or Win32::Registry

**Comment by hythm7** [comment]
Sorry for commenting on this closed issue but I have a question.

can someone explain why  this is used:
``` "depends" : [ {"name" : { "by-distro.name" : { "win32" : "Win32::Registry", "" : "" } } } ]```
instead of:
```"depends" : [ {"name" : { "by-distro.name" : { "win32" : "Win32::Registry" } } } ]```

When I parse the dependencies (default distros other than win32), it now looks for a dep  with name empty string "",  sure I can `grep` only for defined values.  but it looks like adding a default `distro.name`  is not needed as long as no default dependency specified. so my question is what is the benefit of adding and empty string dependency, and if there is no benefit can it be removed?
